#!/usr/bin/env python

import sys
import logging
import bifixer.util as util
import bifixer.bifixer as bifixer

def main(argv):
    try:
        util.logging_setup()
        args = bifixer.initialization()
        bifixer.main(args)
    except Exception as es:
        tb = traceback.format_exc()
        logging.error(tb)
        sys.exit(1)

if __name__=="__main__":
    main(sys.argv[1:])
