#!/usr/bin/env python

import sys
import logging
import traceback
import bifixer.util as util
import bifixer.monofixer as monofixer

def main(argv):
    try:
        util.logging_setup()
        args = monofixer.initialization()
        monofixer.main(args)
    except Exception as es:
        tb = traceback.format_exc()
        logging.error(tb)
        sys.exit(1)

if __name__=="__main__":
    main(sys.argv[1:])
