
{% set rdir = ".." %}
{% set data = load_setup_py_data(setup_file=''+rdir+'/setup.py', from_recipe_dir=True) %}

package:
  name: bifixer
  version: {{ data.get('version') }}

source:
  path: {{ rdir }}

build:
  string: {{ environ.get('GIT_DESCRIBE_HASH') }}
  preserve_egg_dir: True

requirements:
  build:
    - pip
    - setuptools
    - python>=3.7
  run:
    - python>=3.7

test:
  source_files:
    - tests/*
  requires:
    - pytest
  commands:
    - pushd tests; pytest; popd

about:
  home: https://github.com/bitextor/bifixer
  license: GPL3
  summary: Tool to fix bitexts and tag near-duplicates for removal
